name: Create a new version/release

on:
    workflow_dispatch:

jobs:
    new_version:
        name: Create a new version
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                token: ${{ secrets.TOKEN_FOR_GIT }}

            - name: Create a new version
              shell: bash
              run: |
                  git config --global user.name "Gissehel"
                  git config --global user.email "gissehel@users.noreply.github.com"
                  make release
